version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
  database:
    image: mongo:latest
    container_name: db-mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
  broker:
    image: rabbitmq:3-management
    container_name: msg-broker
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 5672
      - 15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      - database
      - redis

  node:
    build: .
    container_name: node-backend
    ports:
      - 5000:5000
    command: pm2-runtime start build/index.js
    depends_on:
      broker:
        condition: service_healthy
        
