version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  database:
    image: mongo:latest
    container_name: db-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
  broker:
    image: rabbitmq:3-management
    container_name: msg-broker
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
